### ISSUE TITLE
Max Vending Zeny Limit Setting

### ISSUE THREAD

**Issue by Everade** [MStr3am/NEMO#128]
This isn't an actual issue related to an existing diff.
It's more a **request** to ask for an option to increase the Max Vending Zeny Limit on 2015clients+

I'm using 2015-09-16aRagexe

At the current state you always get a pop up window which tells you that you've reached the max limit ov 1b zeny, which i guess is a new client-side limit.

**Would be great if we had a diff to increase it up to 2'147'483'647 (as max int/int32 limit)**
Or if we could increase it by ourself by giving an input.

**Comment by dastgir** [comment]
There's check box on bottom(while putting items into vend), uncheck it, then it should allow I guess..

**Comment by Everade** [comment]
Just tested, **does not make any difference**, the pop up still persists.

> You entered more than 1 Billion Zeny ,
> the price will be set to 1 Billion
> Zeny.

**Comment by MStr3am** [comment]
Ok so i see a hardcoded comparison with 1 billion which can be modified via patch. Any idea which date onwards this 1B limit checking started?

**Comment by MStr3am** [comment]
I have added a patch. Try it out.

**Comment by Everade** [comment]
Just tested, but nothing changed, still having the same issue.
I have no idea with which client date this started.

However i'm using
**2015-09-16aRagexe**

**Comment by Everade** [comment]
Any news on this?

**Comment by Everade** [comment]
bump

**Comment by Everade** [comment]
@MStr3am Any news on this?

**Comment by MStr3am** [comment]
Well i modified all the relevant 1B checks but finally the price being set is still 1B. I am wondering if there is a limit set in the server side that I am missing. do you know of any?

**Comment by MStr3am** [comment]
Done. Check now.

**Comment by Everade** [comment]
---------------------------
Patch Error
---------------------------
Change Vending Limit [Experimental] : Failed in Step 2 - Comparison missing
---------------------------
OK   
---------------------------

**Comment by MStr3am** [comment]
check now.

**Comment by MStr3am** [comment]
well? i am going to close this tomorrow in case the patch has no more issues

**Comment by Everade** [comment]
@MStr3am 

Still not working.
The patch applies just fine.

But ingame nothing changed.

Here's a screenshot, as soon as you go at least 1 zeny above the 1billion cap  (i've set it to 2b using your diff)

![screengatheringro032](https://cloud.githubusercontent.com/assets/12261601/15910311/96014552-2dca-11e6-8314-e0dbc0850f73.jpg)

**Comment by MStr3am** [comment]
did you set the limit server side as well?

**Comment by secretdataz** [comment]
@MStr3am [Seems to be working](https://github.com/rathena/rathena/issues/1069#issuecomment-223527839)

**Comment by Everade** [comment]
**No, still doesn't work.**
And yes, server side limit is set to 2b

**Comment by MStr3am** [comment]
which client date did you use? 2015-09-16aRagexe?

**Comment by Everade** [comment]
2015-09-16aRagexe **as stated above yes**

**Comment by Everade** [comment]
@MStr3am Any update on this?

**Comment by Everade** [comment]
@MStr3am Any update on this?

**Comment by Everade** [comment]
2015-09-16aRagexe **as stated above** yes

**Comment by Everade** [comment]
@MStr3am Any update on this?
